[package]
name = "darwin-rs"
version = "0.2.0"
authors = ["Willi Kappler, grandor@gmx.de"]
license = "MIT"
description = "Evolutionary algorithms library written in Rust."
readme = "README.md"
repository = "https://github.com/willi-kappler/darwin-rs"
exclude = ["*.png", "example", "target"]
keywords = ["evolutionary", "algorithm", "EA", "darwin"]
documentation = "https://willi-kappler.github.io/darwin-rs"

[dependencies]
jobsteal = "0.5"
quick-error = "1.1.0"
# clippy = "*"
