[package]
name = "ocr"
version = "0.1.0"
authors = ["Willi Kappler, grandor@gmx.de"]

[dependencies]
time = "0.1"
rand = "0.3"
image = "0.10"
imageproc = "0.6"
freetype-rs = "0.8"

darwin-rs = {path = "../../../darwin-rs"}
